/* tslint:disable */
/* eslint-disable */
/**
 * Geocoding OSM
 * With the Geocoding OSM service places can be searched based on OSM data. The search is based on an address, text input or a geographical position.
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Corner coordinates of the area surrounding the place.
 * @export
 * @interface BoundingBox
 */
export interface BoundingBox {
    /**
     * The longitude value in degrees (WGS84/EPSG:4326) from west to east.
     * @type {number}
     * @memberof BoundingBox
     */
    left: number;
    /**
     * The latitude value in degrees (WGS84/EPSG:4326) from south to north.
     * @type {number}
     * @memberof BoundingBox
     */
    bottom: number;
    /**
     * The longitude value in degrees (WGS84/EPSG:4326) from west to east.
     * @type {number}
     * @memberof BoundingBox
     */
    right: number;
    /**
     * The latitude value in degrees (WGS84/EPSG:4326) from south to north.
     * @type {number}
     * @memberof BoundingBox
     */
    top: number;
}

/**
 * Check if a given object implements the BoundingBox interface.
 */
export function instanceOfBoundingBox(value: object): value is BoundingBox {
    if (!('left' in value) || value['left'] === undefined) return false;
    if (!('bottom' in value) || value['bottom'] === undefined) return false;
    if (!('right' in value) || value['right'] === undefined) return false;
    if (!('top' in value) || value['top'] === undefined) return false;
    return true;
}

export function BoundingBoxFromJSON(json: any): BoundingBox {
    return BoundingBoxFromJSONTyped(json, false);
}

export function BoundingBoxFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoundingBox {
    if (json == null) {
        return json;
    }
    return {
        
        'left': json['left'],
        'bottom': json['bottom'],
        'right': json['right'],
        'top': json['top'],
    };
}

export function BoundingBoxToJSON(value?: BoundingBox | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'left': value['left'],
        'bottom': value['bottom'],
        'right': value['right'],
        'top': value['top'],
    };
}

