/* tslint:disable */
/* eslint-disable */
/**
 * Geocoding OSM
 * With the Geocoding OSM service places can be searched based on OSM data. The search is based on an address, text input or a geographical position.
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DetailLevel = {
    COUNTRY: 'COUNTRY',
    STATE: 'STATE',
    PROVINCE: 'PROVINCE',
    CITY: 'CITY',
    SUBURB: 'SUBURB',
    MAJOR_STREETS: 'MAJOR_STREETS',
    MAJOR_AND_MINOR_STREETS: 'MAJOR_AND_MINOR_STREETS',
    BUILDING: 'BUILDING'
} as const;
export type DetailLevel = typeof DetailLevel[keyof typeof DetailLevel];


export function instanceOfDetailLevel(value: any): boolean {
    for (const key in DetailLevel) {
        if (Object.prototype.hasOwnProperty.call(DetailLevel, key)) {
            if (DetailLevel[key as keyof typeof DetailLevel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DetailLevelFromJSON(json: any): DetailLevel {
    return DetailLevelFromJSONTyped(json, false);
}

export function DetailLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailLevel {
    return json as DetailLevel;
}

export function DetailLevelToJSON(value?: DetailLevel | null): any {
    return value as any;
}

