/*
 * Geocoding OSM
 *
 * With the Geocoding OSM service places can be searched based on OSM data. The search is based on an address, text input or a geographical position.
 *
 * The version of the OpenAPI document: 1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.geocoding.osm.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.geocoding.osm.Model
{
    /// <summary>
    /// Defines DetailLevel
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DetailLevel
    {
        /// <summary>
        /// Enum COUNTRY for value: COUNTRY
        /// </summary>
        [EnumMember(Value = "COUNTRY")]
        COUNTRY = 1,

        /// <summary>
        /// Enum STATE for value: STATE
        /// </summary>
        [EnumMember(Value = "STATE")]
        STATE = 2,

        /// <summary>
        /// Enum PROVINCE for value: PROVINCE
        /// </summary>
        [EnumMember(Value = "PROVINCE")]
        PROVINCE = 3,

        /// <summary>
        /// Enum CITY for value: CITY
        /// </summary>
        [EnumMember(Value = "CITY")]
        CITY = 4,

        /// <summary>
        /// Enum SUBURB for value: SUBURB
        /// </summary>
        [EnumMember(Value = "SUBURB")]
        SUBURB = 5,

        /// <summary>
        /// Enum MAJOR_STREETS for value: MAJOR_STREETS
        /// </summary>
        [EnumMember(Value = "MAJOR_STREETS")]
        MAJOR_STREETS = 6,

        /// <summary>
        /// Enum MAJOR_AND_MINOR_STREETS for value: MAJOR_AND_MINOR_STREETS
        /// </summary>
        [EnumMember(Value = "MAJOR_AND_MINOR_STREETS")]
        MAJOR_AND_MINOR_STREETS = 7,

        /// <summary>
        /// Enum BUILDING for value: BUILDING
        /// </summary>
        [EnumMember(Value = "BUILDING")]
        BUILDING = 8
    }

}
